### ISSUE TITLE
Documentation for 2.3

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/ConfinementTool#17]
- [ ] Home Page

   - [ ]New  Version and Release Notes

- [ ]  New Project

- [ ]  Load Inputs

- [ ]  Calculate Margins

- [ ]  Confinement Segments

- [ ]  Moving Window

- [ ]  Integrated Width
- [ ]  Method
- [ ]  Confinement Calculation Method
- [ ]  About project mode
- [ ]  Standard Inputs

**Comment by joewheaton** [comment]
Seems this was closed by accident? It still needs doing.
