### ISSUE TITLE
Identifying Constrictions @ Bridges and Crossings (i.e. confinement on both side)

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/ConfinementTool#29]
@Hornbydd wrote:

> David/Joe,
> I have worked up the model logic for identifying confinements caused by bridges.  As this has required some logic that I think works I would like to run it passed you for a sanity check, as such I have documented it in the attached document.
> 
> Duncan

And came up with:

## Identifying confinements created by bridges
The document shows how a bridge confinement polyline is generated.
The logic follows as:
1.	From OS Topo Area select polygon where DescriptiveGroup = 'Road Or Track,Structure'
2.	Subset from this selection only the polygons that intersect channel centreline
3.	Buffer selection – currently I’m using 15m the same as buffering out from the channel for Joe’s confinement tool
4.	Convert valley bottom to a polyline and intersect with buffer
The four figures below show four scenarios on the Derwent (6 where identified). Black lines are the bridge confinements.
![fig1](https://user-images.githubusercontent.com/9723905/44887126-c4f8c400-ac87-11e8-8850-4116ca349670.png)
Figure 1 Confinement generated on both sides.

![fig2](https://user-images.githubusercontent.com/9723905/44887131-cc1fd200-ac87-11e8-8b41-37816908b82d.png)
Figure 2 No confinement generated.

![fig3](https://user-images.githubusercontent.com/9723905/44887132-cc1fd200-ac87-11e8-85fb-8587652f5a06.png)
Figure 3 Confinement identified on one bank.

![fig4](https://user-images.githubusercontent.com/9723905/44887133-cc1fd200-ac87-11e8-8645-fa0e2312420c.png)
Figure 4 Inconsistent attribution in OS Top Area means this bridge is not identified. But in this case it is adjacent to a confinement line. Outflow of Lake Bassenthwaite.

**Comment by joewheaton** [comment]
David Sear (needs to make himself a GitHub account) wrote:

>  Looks like it works! The challenge will be legacy infrastructure where this fines the channel but the OS knows the bridge bed has gone!
> 
> Good work Duncna
> 
> David

**Comment by joewheaton** [comment]
Nice one @Hornbydd . Just make sure we refer to the special case of confinement on both sides as a 'constriction' ;).

So this makes sense you can identify this just fine with OS data for bridges.  A few thoughts:

1. Are you able to use the confinement tool's identification of 'active confining margins' and separate accounting to reproduce this result (note we actually already calculate the special case of confinement on both-sides as a % of reach experiencing constriction)? It of course only calculates this based on the network line segmentation. So if short segments are imposed at crossings, it can get a 100% of reach is constricted....
2.  Do we want to calculate the dw/dx (change in width with respect to distance) as we transition from the reaches above crossings and below to measure the degree of constriction (as opposed to the proportion of reach length experiencing a 'constriction' or up against active confining margins on both sides?

After we hash out what I've labeled a 'discussion' here and we work out the manual geoprocessing steps, we can start a new ticket that refers to this one for a 'enhancement'.... if we decide to incorporate it into the tool.

**Comment by Hornbydd** [comment]
@joewheaton -  My current model logic is creating the geometries, those black lines in the images above, it does not attempt to attribute them in any way, which is the same as the current confinement tool nor transfer this information to the river centreline. To do that would require a load of code to be developed. I can see the following issues:

- The bridge confinement lines may "overlap" with the valley bottom confinement lines, how to merge these two when splitting the network?
- The confinement tools logic is to build the confinement lines from valley bottoms and use this to segment and attribute network, there is no mechanism for accepting a second dataset (my bridge confinement lines).

**Comment by Hornbydd** [comment]
I have extended the model logic to count how many confinement margins there are to a bridge, there can only ever be 1 or 2 and have added a field that codes the margin as Confined (1) or Constricted (2).  This is not quite the same as the existing confinement tool which encodes such information into the segmented centre line. To do that will require more extensive coding.

**Comment by Hornbydd** [comment]
So I've started looking at the logic of how to "burn" the bridge confinement margins created by the model above into the river centre line. See image below:

![image](https://user-images.githubusercontent.com/22773948/45375067-daf17780-b5eb-11e8-95a9-56d2e3dc22c2.png)

I need @joewheaton or @dsear to make an executive decision on which part of the intersection that you want to keep?

**Comment by dsear** [comment]
Looking at this higher resolution data brings out these awkward points. My feeling is keep it simple and relevant so Burn the Centreline where the two confining margins overlap (smaller of the Centrelines as this strictly is the confined reach. The extension will be a small confined margin that your buffer will probably remove as <10m of confinment. Good work.
PS have you both managed to see my GIThub Issues...just checking I'm doing it properly!

**Comment by Hornbydd** [comment]
@dsear  - Yes I can see your issue #34, you are now a github master!

**Comment by Hornbydd** [comment]
OK Some good news, I have worked up the logic that takes the bridge confinement margins, assigns left/right side, "burns" this back into the RawConfiningState layer created by the Confinement Tool and then adjusts the IsConstricted and IsConfined fields to the same as what is generated by the confinement tool.

So this new model tool is designed to be run after 1) you can created the initial confinement data and 2) constructed the bridge confinement margins using the tool above.

The inputs require the original river centreline to be flowing from source to sea and is a single measured polylineM featureclass where measure is increasing from the source end. Such a dataset would exist as this is the requirement of the river bathymetry tool.

It's a meaty model, calling two sub-models!

![image](https://user-images.githubusercontent.com/22773948/45499294-0a32f080-b774-11e8-9adf-0d6e1cfaf62d.png)

The tool creates a new layer "burning" or you can think of it as "stamping" the bridge confinement into the centreline (RawConfiningState). Output appears to be looking good!

_Click on image to enlarge_
![image](https://user-images.githubusercontent.com/22773948/45499939-503c8400-b775-11e8-9939-9b064cde7545.png)

Final step is to smarten up the tool interface and a little bit of documentation.

All these tools are currently existing in a toolbox as model tools, below is a screen shot of the toolbox as it stands

![image](https://user-images.githubusercontent.com/22773948/45499808-0784cb00-b775-11e8-9c0f-4c3c1f950954.png)

**Comment by joewheaton** [comment]
This seems to be working well now. Nice one @Hornbydd and I agree with @dsear on his 'executive decision' to your question.
