### ISSUE TITLE
Extracting Confinement Margin Erodability

### ISSUE THREAD

**Issue by Hornbydd** [Riverscapes/ConfinementTool#31]
I have extracted out from the UK BGS 1:50K geology datasets covering the Derwent study region the descriptive texts. David then identified which geologies were erodible or non-erodible.  His logic was

> (1) All bedrock is non-erodible, (2) All superficial with sand and gravel are erodible and (3) All superficial without sand and gravel in the description is non-erodible.

The Erodibility values are simply **Y** for yes, **N** for No and **X** for unknown/water in the superficial layer.

These values are store in the Excel spreadsheet ([UC1476_Geology_LookUp.xlsx](https://github.com/Riverscapes/ConfinementTool/files/2356340/UC1476_Geology_LookUp.xlsx)).

The idea is to build a model that will intersect the confinement margins with the geology and code into erodible values. A confinement margin line can intersect multiple geologies along its length as shown below.

![image](https://user-images.githubusercontent.com/22773948/45148628-9f0b7c00-b1bf-11e8-8af0-541f7a9991d2.png)

In this example the proposed output would be a non-spatial table with one row recording summed lengths.

```
MarginID   Bed_Erod_N   Sup_Erod_Y   Sup_Erod_N   Sup_Erod_X
66              114            90              0           24
```
Recording it in this manner will allow you to identify when there is no superficial geology and the river is passing through bedrock as superficial will have zero lengths.

This approach requires me to create a margin ID field whilst running the confinement tool, easy to do.

**Comment by joewheaton** [comment]
So @Hornbydd this is cool, but I want to make sure I understand what you're doing. As best I can tell, you're intersecting the _active confining margins_ with a binary erodibility layer of _Y_ or  _N_ for erodibility and then if its a yes you tally up the length? Is that right? If so, where do we go with this? To some, erodiblity might imply how erodible. I guess what we're most interested in is what type of source material we're eroding (e.g. alluvial deposits of alluvial fans or terraces vs. resistant bedrock, vs. friable bedrock, vs. colluvium of fans or tallus lopes, vs. regolith, vs. soils). There are lots of places to take this, but @dsear and you and I should flesh out where we are hoping to take this. Cool stuff.

**Comment by dsear** [comment]
Thanks @joewheaton and @Hornbydd - I think we're at the first stage in this process and as such we're interested in simplifying the potential drivers of geomorphic change (see discussion point I put up this week). Whilst knowing the TYPE of deposit a confining margin is eroding, in terms of the geomorphic response to a very large flood I've asssumed the first order control is - is it erodible (Y/N). If YES we might then consider the scale of the potential contribution (which in an ideal world would be an estimate of area of erodible confining margin - Length x height (from DEM), It MIGHT be possible to extract further information but the BGS codes are compex so it might be a word search.  What woudl we do with this information though? At best ew might decide if the source material (after screening for erodible) is sands/gravels/fines (soil and clay)/boulders, but unclear if these are in the BGS drift/solid codes? Thoughts?

**Comment by Hornbydd** [comment]
Tool is complete and no further development is currently planned. It is likely that it will require further development if we try to roll it out for national level processing.
