### ISSUE TITLE
Generating the scale of erodibility

### ISSUE THREAD

**Issue by Hornbydd** [Riverscapes/ConfinementTool#38]
@joewheaton and @dsear I have worked up a tool that will generating the scale of erodibility.  This is computed as length of confinement margin * elevation where elevation is the difference in mean elevation of margin minus mean elevation of river centreline segment. The assumption is that the river centreline is always lower than the confinement margin.

Tool logic is:

1.  The tool takes the centroid of the margin and uses that to locate nearest segment of river (what is the raw confining state dataset).
2.  Explode the margins and centreline segments into their constituent vertices and extract elevation from a DTM. The DTM used is the OS 5m Terrain DTM.
3.  Compute the mean elevation of margin (_e1_) and river centreline segment (_e2_).
4.  Transfer over the margin length (_L_)  and then compute the scale as _L_ * (_e1_-_e2_).
5.  Export to a table with margin ID so that it can all be joined to the original confinement margin layer.

As an image here is a zoomed in example:

![Example](https://user-images.githubusercontent.com/22773948/48063066-cc72a700-e1bb-11e8-8a92-a8788e9acc10.png)
_Note: all vertices have an elevation its simply label placement priority that is causing some not to display._

MarginID	| MarginMean	| CentrelineMean | Length | Erodability Area
-- | -- | -- | -- | --
5 | 63.45 | 59.47 | 519.42 | 2063.60

The model is below and has been given a nice user friendly interface.

![Model](https://user-images.githubusercontent.com/22773948/48063359-ab5e8600-e1bc-11e8-9698-419517e51666.png)

Tool interface:

![Tool interface](https://user-images.githubusercontent.com/22773948/48064423-a64f0600-e1bf-11e8-8095-c42e1ef76356.png)

**Comment by dsear** [comment]
@Hornbydd this is good work. My only challenge to this is if you look at the shaded DEM relief you can see that the confining margin is at the foot of the slope, and thus underestimates the true height of the cliff. Can one add in a 15m buffer taking the heighest elevations in that buffer?

**Comment by Hornbydd** [comment]
@dsear that logic can certainly be spliced into the model but I think it would _overestimate_ in scenarios when the confinement is not a terrace but something like a wall in an urban setting. Of cause it may be better to over estimate than under estimate?

So your suggestion would be this, green dot identifies highest point

![Example](https://user-images.githubusercontent.com/22773948/48070542-ff269a80-e1cf-11e8-97f6-80e6022ce9b6.png)

I would be keen to keep the existing computation and add to the output table the same computation but based upon difference of highest elevation in buffer (green dot) - centreline mean. Then we have two values to compare against? Shall I do that?

The buffer distance can be set at 15m but can be easily changeable. I think the big assumption is that the river width but be at least half the width of the buffer distance otherwise it will pick up left and right bank!

**Comment by dsear** [comment]
@Hornbydd I see what you mean, is it possible to buffer on one side only (ie buffer the confining margin but always on the side of the centreline the confining margin is located (ie if on right bank, then buffer to right side of confining margin line?).  I'd keep both options for now as you suggest, because IF there's little difference then it suggests floodplain or low terrace.  If they are quite difference as in the one you show above, then you go with largest area.  It woudl only be for Erodible margins so walls woudl presumably NOT be an erodible margin.

**Comment by Hornbydd** [comment]
@dsear  Ha! Good point one would hope walls would not be eroding! :) 

I was thinking at this point they are the intersection lines with the floodplain and as such not tagged in anyway to say if they are anthropogenic, hence my though of overestimating.

Buffering left and right requires you to know which side of the river that confinement margin is on. That is not encoded into the dataset by their confinement tool. It would also require the confinement lines to be created in a consistent direction so when you buffer out it is on the correct side of the margin. I think this is doable but may require me to edit their source code (which I've been doing anyway).

**Comment by Hornbydd** [comment]
@dsear OK have been able to amend confinement tool source code to pass over the L/R bank side information into the Confinement Margins layer  (@joewheaton I've pushed up a new version of the confinement toolbox on my forked version). This allows me to buffer out in the correct direction for Left and Right margins which can then be used to extract the highest elevation value within the 15m buffer. This all passes back into the main output table and a second erodible scale value is computed.  I just need to tied up the interface as I expose the buffer distance as an optional parameter. The tool should then be done.

**Comment by Hornbydd** [comment]
@dsear and @joewheaton for completeness here is a screen shot of the final tool and the output table below. You can optionally change the buffer width, this is set to a default of 15m. The output table has for each margin an erodability scale based upon the mean elevation along the polyline and the maximum elevation within the buffer region.

![Screenshot](https://user-images.githubusercontent.com/22773948/48126106-410b1b80-e278-11e8-94b3-3629c22fc63d.png)

**Comment by Hornbydd** [comment]
I consider this tool complete and this discussion closed.
