### ISSUE TITLE
Calculating sinuosity

### ISSUE THREAD

**Issue by Hornbydd** [Riverscapes/ConfinementTool#40]
@dsear - OK just wanted to clarify the actual working out of the sinuosity of a segment when compared to the valley centre line. Turns out when I go back to our scribblings, what was clear as day then is now just a jumble of blue lines! :)

![Mad minds!](https://user-images.githubusercontent.com/22773948/48274627-a6f3d080-e43b-11e8-888e-58a9f260cd02.jpg)

Below are two scenarios that I will have to deal with, the segment in question is highlighted in blue, valley centre line is purple.

### Example 1- Segment intersects valley centre line 

![Example 1](https://user-images.githubusercontent.com/22773948/48274710-ce4a9d80-e43b-11e8-83b6-2b0171305b77.png)

### Example 2- Segment never intersects valley centre line

![Example 2](https://user-images.githubusercontent.com/22773948/48275089-9d1e9d00-e43c-11e8-8dab-9109d7b09acd.png)

Are these examples how you expect sinuosity to computed? I should be able to prototype a tool fairly quickly as a serendipitous outcome of generating routes from a network dataset is that the output is a calibrated Polyline M which means I can hook into the M values embedded in the line for quick and simple calculations.

**Comment by Hornbydd** [comment]
@dsear - OK I have gone ahead to constructed a tool that computes sinuosity. It hooks into the fact that the output of the network dataset trace is a calibrated PolylineM featureclass. The tools logic is:

- Select segments that match specified BranchID.
- Extract end points of selected segments.
- Locate on route and extract measure values, this allows the valley line segment length to be computed.
- Using a temporary join pass over valley centre line segment lengths and compute sinuosity of segments.

This is the model:

![Model](https://user-images.githubusercontent.com/22773948/48361781-2d0d5280-e69a-11e8-944b-3ade5c3b86ad.png)

I have constructed a tool interface for the model:

![Tool](https://user-images.githubusercontent.com/22773948/48361699-f5060f80-e699-11e8-8a22-6a27462b00ca.png)

**Comment by dsear** [comment]
@Hornbydd well done for ploughing ahead. What type of values come out for this? What is more critical is the valley centreline and from this the ability to calculate Valley slope. and to work out segments for land intensity and proportion of valley flood at risk of Geomorphic change.  So I think these are the next foci.
The problem of Valley centreline outside this pilot study is a constraint but presumably we might a) fix it in time or b) EA might commission OS to produce one nationally?
Onwards!

**Comment by Hornbydd** [comment]
Here are the current basic stats on sinuosity for the main stem of the Derwent

![Stats](https://user-images.githubusercontent.com/22773948/48366511-0f45ea80-e6a6-11e8-9359-9b883f02ea03.png)

The really high value just happens to be the very meander I was looking at in #41 !

![max value](https://user-images.githubusercontent.com/22773948/48366609-53d18600-e6a6-11e8-85cd-2de54cbc5180.png)

**Comment by dsear** [comment]
OK seem sensible - highest bend curvature relative to valley length gets highest sinuosity. 
good work @Hornbydd

**Comment by Hornbydd** [comment]
I consider this tool complete so I am closing this discussion.
