### ISSUE TITLE
Segmenting floodplain (to allow other metrics to be computed)

### ISSUE THREAD

**Issue by Hornbydd** [Riverscapes/ConfinementTool#41]
@dsear - So another key processing step is to partition up the floodplain into polygons which can be used to aid in computing other metrics (e.g. the land cover).

Below is a screenshot of the available datasets to work with.

![Datasets](https://user-images.githubusercontent.com/22773948/48364283-ea4e7900-e69f-11e8-92b0-bb51c4b67bbf.png)

We discussed creating cross sections across the floodplain that could be used to create polygons that can then be used to "cookie cut" other datasets (e.g. LCM data). 

Creating cross sections only makes sense if it is done from the valley centreline (#44). Below are spoofed up examples (black are cross sections built from the valley centreline, red are built from the river centreline). 

My initial logic to construct these cross sections is to find the nearest point on the floodzone boundary, hence kinks can be introduced. I have subsequently opted for a slightly different approach as discussed in #44. 

![Spoofed examples](https://user-images.githubusercontent.com/22773948/48364917-92b10d00-e6a1-11e8-9f2c-2bd1838af329.png)

So questions are:

- If the valley centreline is used to partition up the floodzone polygons what stepping distance along the centreline should be used? Be aware that this stepping distance WILL NOT align with the segmenting distance of the river centreline.

- Be aware one or more river segments could/would exist within a floodplain partition polygon, especially if the stepping distance along the valley centreline is larger than the segmenting distance of the river centreline (currently set at 500m + bridge points - see #37 ).

But a bigger problem is how to stop clipping out floodplain tributaries! Below lets say floodplain stepping distance is set to 1Km, you create the cross sections and enclose using the floodzone boundary. The 2 black areas make sense but the third red partition captures a tributary junction with it's own floodplain. How do we stop it going u/s to the very source and include everything u/s?

![Problem](https://user-images.githubusercontent.com/22773948/48365712-95acfd00-e6a3-11e8-9ae5-3c5a428bfc84.png)

One approach is to create boxes as shown below, but this would under estimate for the same scenario.

![Box it!](https://user-images.githubusercontent.com/22773948/48366276-3a7c0a00-e6a5-11e8-9e08-279aaab91a2e.png)

**Comment by dsear** [comment]
So the task then becomes allocating a slope and catchment area based on the valley centreline derived polygons to the Channel segments. @joewheaton got any thoughts on this before @Hornbydd goes much further? Personally I don't have a problem with the tributary issue you show here I think that's just what you get when a trib joins.  In terms of land cover I guess we need to agree a simple classification from the cover types you show to some simple ones (High, medium, low intensity land cover).

**Comment by Hornbydd** [comment]
Tool is complete and no further development is currently planned. It is likely that it will require further development if we try to roll it out for national level processing.
