### ISSUE TITLE
UK LCM2015 - Land cover lookup values

### ISSUE THREAD

**Issue by Hornbydd** [Riverscapes/ConfinementTool#42]
@dsear - please find attached an excel document, it has the LCM 2015 classes and I need you to assign your land intensity values to them. 

Once you have edit it please upload it to this discussion.

[LCMClassLookup.xlsx](https://github.com/Riverscapes/ConfinementTool/files/2575913/LCMClassLookup.xlsx)

Once you provide them I can re-code the CEH LCM 2015 25m raster into an intensity map.

**Comment by Hornbydd** [comment]
Proposed LCM reclass. Class number is the pixel value in the raster, CEH LCM land class and our reclassified  landuse intensity.

Class_number | LCM2015_class | Landuse_Intensity
-- | -- | --
1 | Broadleaved woodland | Very Low
2 | Coniferous Woodland | Low
3 | Arable and Horticulture | Moderate
4 | Improved Grassland | Low
5 | Neutral Grassland | Low
6 | Calcareous Grassland | Low
7 | Acid grassland | Very Low
8 | Fen, Marsh and Swamp | Very Low
9 | Heather | Very Low
10 | Heather grassland | Very Low
11 | Bog | Very Low
12 | Inland Rock | Very Low
13 | Saltwater | Very Low
14 | Freshwater | Very Low
15 | Supra-littoral Rock | Very Low
16 | Supra-littoral Sediment | Very Low
17 | Littoral Rock | Very Low
18 | Littoral sediment | Very Low
19 | Saltmarsh | Very Low
20 | Urban | High
21 | Suburban | High

**Comment by Hornbydd** [comment]
Here is a before and after screen shot of LCM 2015 data reclassified from original CEH land cover classes to our Landuse intensity classes.

![uc1476_derwent_lcm](https://user-images.githubusercontent.com/22773948/48716307-f17d0600-ec0e-11e8-9930-af79ac4e64e3.png)

**Comment by dsear** [comment]
Looks great Duncan! Remember this is an iterative classification that others (stakeholders like farmers) might classify differently.
We need to add road and rail network to this making them moderate intensity features in the landscape.
Thanks
David

Sent from my iPhone

On 19 Nov 2018, at 15:22, Duncan Hornby <notifications@github.com<mailto:notifications@github.com>> wrote:


Here is a before and after screen shot of LCM 2015 data reclassified from original CEH land cover classes to our Landuse intensity classes.

[uc1476_derwent_lcm]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F22773948%2F48716307-f17d0600-ec0e-11e8-9930-af79ac4e64e3.png&data=01%7C01%7Cd.sear%40soton.ac.uk%7Cd23acfaf62434464300a08d64e32db31%7C4a5378f929f44d3ebe89669d03ada9d8%7C1&sdata=9CPK7UDOb4yk1wF4iAiFdaxx6EusNgV%2FM%2BawbG6t0T4%3D&reserved=0>

**Comment by Hornbydd** [comment]
@dsear - by "adding roads" are you wanting me to convert rail and road lines from OS into rasters and "stamp" them onto the LCM dataset, coding them as moderate. Was that what you were thinking? This is what I am thinking.

**Comment by dsear** [comment]
Hi Duncan yes I think that’s exactly what I am thinking ☺

David

Professor David Sear
School of Geography
University of Southampton
++44 (0)2380 592215(Office)
++44 (02380 594614 (Direct)
Email:d.sear@soton.ac.uk
Twitter:@sedimentsystem
ORCID:0000-0003-0191-6179<http://orcid.org/0000-0003-0191-6179>
http://www.southampton.ac.uk/geography/staff_profiles/academic/ds5.html
http://www.nercpatches.org
http://www.dunwich.org.uk<http://www.dunwich.org.uk/>

**Comment by Hornbydd** [comment]
All,

I have completed the LCM preparation tool. It takes the OS topographic area data, selects out polygons tagged as road/rail, converts the selection to a raster and then mosaics this onto the LCM 2015 raster. It then finally joins a lookup table so the data can be symbolised  by land use intensity. This approach retains the original LCM pixel values if they were ever required.

Model is:

![Model](https://user-images.githubusercontent.com/22773948/48840172-c9fc7980-ed85-11e8-868e-47c80db680d1.png)

The tool interface is shown below.

![Tool Interface](https://user-images.githubusercontent.com/22773948/48839789-7e959b80-ed84-11e8-8b8c-16ddadb515fd.png)

### Limitations

A limitation is that OS roads and rail polygons that fall within pixels that are urban in the LCM will be reclassified to rail/roads (30/31). Urban is a high intensity land cover so those pixels are being "downgraded" in their severity.

Some thin roads will not be captured as pixels as they fall below the 25m pixel threshold size.

**Comment by Hornbydd** [comment]
I consider this tool effectively completed, if any changes are going to occur it will be with the lookup table and changes in what is perceived as intense land use.
