### ISSUE TITLE
Computing stream power Index

### ISSUE THREAD

**Issue by Hornbydd** [Riverscapes/ConfinementTool#43]
@dsear - A metric that requires computing is stream power. In the email you had defined stream power as: 

> stream power = (Catchment area * Slope) / 1:1000yr flood poly width

So firstly I have 3 questions that need clarification:

1. Is the catchment area for the u/s end point of the segment or d/s end point? I am assuming it is for the d/s end.
2. The slope is the valley centre-line slope for the segment?
3. The flood poly width is the width measured across the floodplain from a single location, taken from the centre point of the segment snapped to the valley centre-line.

So using the example below you would expect stream power to be:

![Example](https://user-images.githubusercontent.com/22773948/48412764-985c3080-e73d-11e8-9277-364ccb968645.png)

(Catchment area in m2 * Slope in m/m) / width in m - not sure what the output units would be.

(370497500 * ((63.2 - 62.8) / 451) / 141) = **2,330.5**

Please confirm I have understood how stream power should be computed?

**Comment by Hornbydd** [comment]
@dsear - tapping into our existing work...

Our UC1168 project on fine sediment created some 300,000+ sampling points along the CEH network for which I computed a catchment area for every point, if I remember correctly that was weeks of work.

These points were snapped to the old EA DRN which was the forerunner to the OS WaterLayer. Dropping points on loops and points that never snapped, I have 293,794 points cover England and Wales which have a polygon that is the delineated catchment boundary.

![Sampling points](https://user-images.githubusercontent.com/22773948/48419993-3c9ba280-e751-11e8-9a8f-927a45758f51.png)

Now its **very important to understand** that MANY of these points failed to create valid catchment area, i.e. source of river was not in catchment polygon for all sorts of technical reasons. How many I don't know yet as that relies me merging the datasets which are currently separated out into Hydrometric Areas, but it's probably safe to assume several hundred thousand points are valid.

These points were 500m spaced, so it's possible to select one that is reasonably near.

So my proposal is that we choose the nearest VALID catchment point and extract the area from that. Be aware the nearest VALID one could be U/S or D/S and may be more than 1km away (e.g. because there are several failed sampling points is a row). In the image below this is what I see happening, are you happy with this approach?

![Example](https://user-images.githubusercontent.com/22773948/48421121-bf256180-e753-11e8-9715-15ebc4936c80.png)

I propose this method as we have a dataset that not only gives us a catchment area but it has some sort of quality control on it (source of river in catchment). The alternative is to compute is on the fly with no quality control!

**Comment by Hornbydd** [comment]
@dsear - I have completed the tool that computes the Stream Power Index, a sample of the index mapped back to the segment is shown below:

![Stream Power Index](https://user-images.githubusercontent.com/22773948/49584517-8001bf00-f953-11e8-9e41-28aa74b60127.png)

Things to note, stream power index is calculated as:

> stream power = (Catchment area * Valley Slope) / 1:1000yr flood poly width

So if the elevation u/s and d/s along the valley centreline are the same then slope becomes zero and stream power becomes zero. 

The elevation difference along the  valley centreline can often be negative (eg. u/s = 33.3 and d/s = 36.6). This is not surprising as the valley centreline is a voronoi edge and it's location has been mathematically computed from the floodplain edge so could go "up hill". How I deal with this is to take the absolute positive difference so in this example -3.3 become 3.3. This avoids creating negative stream powers, which I assume are invalid?

The flood poly width is the maximum floodplain width for the segment.

The catchment area is extracted from the flow accumulation raster rather than the originally suggested method above as it is a more generic approach not relying on bespoke existing data. So to ensure that I am actually extracting the catchment area of the channel I use a 50m tolerance on the snap pour tool from the mid-point of the segment. So firstly I am measuring catchment area from the mid-point and secondly the 50m tolerance can fail to identify an appropriate location on the flow accumulation raster. You can only know it has worked by looking at the adjacent u/s and d/s segments assigned catchment areas. In this case only 1 segment has an anonymously small catchment area.

This miss-identification of catchment area is a common problem and not something that can be easily resolved. What is easy is to spot when it has occurred as catchments areas must increase in a d/s direction, not get smaller then bigger then. So I am thinking of adding to the tool a process to flag up anomalous reaches so you can either drop them from subsequent analysis or deal with them manually.

**Comment by Hornbydd** [comment]
Came across this paper:

https://www.fluvialremotesensing.org/uploads/4/4/1/2/44121747/lea_and_legleiter_in_press.pdf

**Comment by dsear** [comment]
Nice one – thanks. Looks like it contains some similarities to our good efforts but leaves out some key drivers?

Cheers
David

Professor David Sear
School of Geography
University of Southampton
++44 (0)2380 592215(Office)
++44 (02380 594614 (Direct)
Email:d.sear@soton.ac.uk
Twitter:@sedimentsystem
ORCID:0000-0003-0191-6179<http://orcid.org/0000-0003-0191-6179>
http://www.southampton.ac.uk/geography/staff_profiles/academic/ds5.html
http://www.nercpatches.org
http://www.dunwich.org.uk<http://www.dunwich.org.uk/>

**Comment by dsear** [comment]
Hi Duncan OK first off is that slopes need to be realistic so I guess an alternative is to search the sections at the segment boundaries for lowest point and use these (you probably do this anyway?). We cannot have zero slopes so suggest replacing 0 with 0.000001.  Catchment area – I think your solution is correct – flag up nonsense and manually adjust.

Cheers

David

Professor David Sear
School of Geography
University of Southampton
++44 (0)2380 592215(Office)
++44 (02380 594614 (Direct)
Email:d.sear@soton.ac.uk
Twitter:@sedimentsystem
ORCID:0000-0003-0191-6179<http://orcid.org/0000-0003-0191-6179>
http://www.southampton.ac.uk/geography/staff_profiles/academic/ds5.html
http://www.nercpatches.org
http://www.dunwich.org.uk<http://www.dunwich.org.uk/>

**Comment by Hornbydd** [comment]
@dsear - Slope is computed from the valley centreline as shown in the first diagram in this thread. I think it is easiest to assign where slope works out as zero the nominal low value 0.000001 and plug that into the equation.

Will work up tool to flag dodgy catchment values.

**Comment by Hornbydd** [comment]
@dsear - I have created a separate tool that you run on the segmented layer AFTER you have computed the Stream Power Index. It creates a new flag field. It looks for the illogical situation of a catchment area reducing in size as you step downstream a branch. Having run it on the Derwent main stem, only 1 segment fails, so a user would identify the correct catchment area and update the stream power index. I will do this for our data.

For the tool you need to select the segmented layer and set a SQL expression for the branch following the valley centre line.

![Tool](https://user-images.githubusercontent.com/22773948/50089246-2b84fc00-01fd-11e9-81e8-7fe645688bb5.png)

**Comment by Hornbydd** [comment]
Tool is complete and no further development is currently planned. It is likely that it will require further development if we try to roll it out for national level processing.
